version: 0.0
os: linux
files:
  - source: /
    destination: /opt/sample-app
    overwrite: true
hooks:
  ApplicationStop:
    - location: scripts/stopApp.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/startApp.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/healthcheck.sh
      timeout: 300
      runas: root
